# Generated by Django 3.1.3 on 2020-11-19 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('URL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Desktop')], default=2)),
                ('browser', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2020, 11, 19, 22, 44, 7, 702426))),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URL.url')),
            ],
        ),
    ]
