# Generated by Django 3.1.3 on 2020-11-19 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 19, 22, 44, 33, 252858, tzinfo=utc)),
        ),
    ]
