# Generated by Django 3.1.3 on 2020-11-19 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20201119_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 22, 48, 9, 245233)),
        ),
    ]
