# Generated by Django 3.1.3 on 2020-11-19 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URL', '0001_initial'),
        ('visitor', '0004_auto_20201119_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 2, 22, 48, 593122)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='URL.url'),
        ),
    ]
