# Generated by Django 3.1.3 on 2020-11-20 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_auto_20201120_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 19, 55, 49, 318336)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=17),
        ),
    ]
